### ISSUE TITLE
I cannot import filebrowser module into django Installed Apps

### ISSUE THREAD

**Issue by theaterwinner** [smacker/django-filebrowser-no-grappelli#49]
Hello

i am using djang-tinymce-lite-4 wysiwyg editor

and i wanna import file upload to tinymce editor!

but i cannot import the 'filebrowser' module into my project

what is the problem and what can i do ?

below are screenshots of errors

[02/Jan/2019 10:57:41] "GET / HTTP/1.1" 302 0
Internal Server Error: /winbook_insert/
Traceback (most recent call last):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\utils.py", line 64, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\filebrowser\utils.py", line 18, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\filebrowser\templatetags\fb_versions.py", line 8, in <module>
    from filebrowser.base import FileObject
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\filebrowser\base.py", line 16, in <module>
    from filebrowser.utils import path_strip, process_image
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\filebrowser\utils.py", line 20, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\DjangoProject\TheaterWin\TheaterWinBook\views.py", line 193, in winbook_insert
    return render(request, 'TheaterWinBook/winbook_insert.html', {'form': form})  # 템플릿 파일 경로 지정, 데이터 전달
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\loader.py", line 12, in get_template
    engines = _engine_list(using)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\utils.py", line 88, in all
    return [self[alias] for alias in self]
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\utils.py", line 88, in <listcomp>
    return [self[alias] for alias in self]
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\utils.py", line 79, in __getitem__
    engine = engine_cls(params)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 125, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'filebrowser.templatetags.fb_versions': No module named 'Image'
[2019-01-02 10:57:41,590] exception: ERROR - Internal Server Error: /winbook_insert/
Traceback (most recent call last):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\utils.py", line 64, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\filebrowser\utils.py", line 18, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\filebrowser\templatetags\fb_versions.py", line 8, in <module>
    from filebrowser.base import FileObject
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\filebrowser\base.py", line 16, in <module>
    from filebrowser.utils import path_strip, process_image
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\filebrowser\utils.py", line 20, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\DjangoProject\TheaterWin\TheaterWinBook\views.py", line 193, in winbook_insert
    return render(request, 'TheaterWinBook/winbook_insert.html', {'form': form})  # 템플릿 파일 경로 지정, 데이터 전달
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\loader.py", line 12, in get_template
    engines = _engine_list(using)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\utils.py", line 88, in all
    return [self[alias] for alias in self]
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\utils.py", line 88, in <listcomp>
    return [self[alias] for alias in self]
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\utils.py", line 79, in __getitem__
    engine = engine_cls(params)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "C:\Users\jjunest\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\backends\django.py", line 125, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'filebrowser.templatetags.fb_versions': No module named 'Image'
[02/Jan/2019 10:57:49] "GET /winbook_insert/ HTTP/1.1" 500 210603
Not Found: /favicon.ico
[2019-01-02 10:57:50,822] base: WARNING - Not Found: /favicon.ico
[02/Jan/2019 10:57:50] "GET /favicon.ico HTTP/1.1" 404 8907

**Comment by theaterwinner** [comment]
solution) i installed 'pillow' package and it works! thanks!

**Comment by smacker** [comment]
yes. Pillow is a [requirement](https://github.com/smacker/django-filebrowser-no-grappelli#requirements) for filebrowser to work.
